In [11]:
import numpy as np
import pandas as pd

NYPD_data = pd.read_csv("FULL_NYPD_Complaint_Data_Historic_20251112.csv")

NYPD_data.head()

NYPD_data.shape

/var/folders/37/mv21yn416f54tz95t9pwzqxm0000gn/T/ipykernel_6774/3014062942.py:4: DtypeWarning: Columns (20) have mixed types. Specify dtype option on import or set low_memory=False.
  NYPD_data = pd.read_csv("FULL_NYPD_Complaint_Data_Historic_20251112.csv")

(9491946, 35)

In [17]:
NYPD_data['CMPLNT_FR_DT'] = pd.to_datetime(
    NYPD_data['CMPLNT_FR_DT'],
    errors='coerce',
    format='%m/%d/%Y'
)

oldest_date = NYPD_data['CMPLNT_FR_DT'].min()
oldest_date

felony_df = NYPD_data[NYPD_data["LAW_CAT_CD"] == "FELONY"]

felony_df["OFNS_DESC"].unique()

list(felony_df["OFNS_DESC"].unique())

['DANGEROUS DRUGS',
 'CRIMINAL MISCHIEF & RELATED OF',
 'RAPE',
 'ROBBERY',
 'OTHER STATE LAWS',
 'FORGERY',
 'GRAND LARCENY OF MOTOR VEHICLE',
 'GRAND LARCENY',
 'FELONY ASSAULT',
 'MISCELLANEOUS PENAL LAW',
 'POSSESSION OF STOLEN PROPERTY',
 'BURGLARY',
 'THEFT-FRAUD',
 'MURDER & NON-NEGL. MANSLAUGHTER',
 'SEX CRIMES',
 'DANGEROUS WEAPONS',
 'CANNABIS RELATED OFFENSES',
 'ARSON',
 'CHILD ABANDONMENT/NON SUPPORT 1',
 'KIDNAPPING & RELATED OFFENSES',
 'PROSTITUTION & RELATED OFFENSES',
 'INTOXICATED/IMPAIRED DRIVING',
 'HOMICIDE-NEGLIGENT,UNCLASSIFIE',
 'GAMBLING',
 '(null)',
 'HOMICIDE-NEGLIGENT-VEHICLE',
 'NYS LAWS-UNCLASSIFIED FELONY',
 'ENDAN WELFARE INCOMP',
 'CHILD ABANDONMENT/NON SUPPORT',
 'FELONY SEX CRIMES',
 'OTHER STATE LAWS (NON PENAL LA',
 'KIDNAPPING',
 'KIDNAPPING AND RELATED OFFENSES',
 'ABORTION']

In [19]:
violent_offenses = [
    'RAPE',
    'ROBBERY',
    'FELONY ASSAULT',
    'BURGLARY',
    'MURDER & NON-NEGL. MANSLAUGHTER',
    'SEX CRIMES',
    'DANGEROUS WEAPONS',
    'ARSON',
    'KIDNAPPING & RELATED OFFENSES',
    'HOMICIDE-NEGLIGENT,UNCLASSIFIE',
    'HOMICIDE-NEGLIGENT-VEHICLE',
    'FELONY SEX CRIMES',
    'KIDNAPPING',
    'KIDNAPPING AND RELATED OFFENSES'
]

violent_felony_df = felony_df[felony_df["OFNS_DESC"].isin(violent_offenses)]

violent_felony_df.head()

,CMPLNT_NUM,CMPLNT_FR_DT,CMPLNT_FR_TM,CMPLNT_TO_DT,CMPLNT_TO_TM,ADDR_PCT_CD,RPT_DT,KY_CD,OFNS_DESC,PD_CD,...,SUSP_SEX,TRANSIT_DISTRICT,Latitude,Longitude,Lat_Lon,PATROL_BORO,STATION_NAME,VIC_AGE_GROUP,VIC_RACE,VIC_SEX
8,298704210,2024-12-29,18:45:00,12/29/2024,19:45:00,24.0,12/31/2024,104,RAPE,153.0,...,M,NaN,40.796074,-73.967067,"(40.7960743128304, -73.9670667458109)",PATROL BORO MAN NORTH,(null),<18,WHITE HISPANIC,M
11,298702444,2024-12-31,19:10:00,12/31/2024,19:20:00,78.0,12/31/2024,105,ROBBERY,386.0,...,M,NaN,40.668110,-73.965924,"(40.66811, -73.965924)",PATROL BORO BKLYN SOUTH,(null),18-24,BLACK,M
37,298703929,2024-12-31,22:20:00,12/31/2024,22:28:00,120.0,12/31/2024,106,FELONY ASSAULT,109.0,...,M,NaN,40.637557,-74.088608,"(40.637557, -74.088608)",PATROL BORO STATEN ISLAND,(null),25-44,WHITE HISPANIC,F
48,298704199,2024-12-31,21:32:00,12/31/2024,21:44:00,6.0,12/31/2024,106,FELONY ASSAULT,106.0,...,M,NaN,40.729586,-74.000846,"(40.729586, -74.000846)",PATROL BORO MAN SOUTH,(null),25-44,WHITE,L
57,298703733,2024-09-01,10:00:00,09/01/2024,13:00:00,32.0,12/31/2024,104,RAPE,153.0,...,M,NaN,40.815913,-73.945149,"(40.81591307653, -73.9451493066481)",PATROL BORO MAN NORTH,(null),25-44,WHITE,F

In [ ]:
violent_felony_df.loc[:, "CMPLNT_FR_DT"] = pd.to_datetime(
    violent_felony_df["CMPLNT_FR_DT"],
    errors="coerce",
    format="%m/%d/%Y"
)


violent_felony_df = violent_felony_df[
    (violent_felony_df["CMPLNT_FR_DT"] >= "2000-01-01") &
    (violent_felony_df["CMPLNT_FR_DT"] <= "2019-12-31")
]

violent_felony_df["CMPLNT_FR_DT"].min(), violent_felony_df["CMPLNT_FR_DT"].max()

(Timestamp('2000-01-01 00:00:00'), Timestamp('2019-12-31 00:00:00'))

In [32]:
# cols_to_drop = [
#     'CMPLNT_NUM', 'CMPLNT_TO_DT', 'CMPLNT_TO_TM', 'KY_CD', 'PD_CD',
#     'PD_DESC', 'LAW_CAT_CD', 'BORO_NM', 'LOC_OF_OCCUR_DESC',
#     'PREM_TYP_DESC', 'JURISDICTION_CODE', 'PARKS_NM', 'HADEVELOPT',
#     'HOUSING_PSA', 'TRANSIT_DISTRICT', 'VIC_AGE_GROUP', 'VIC_RACE',
#     'VIC_SEX'
# ]

# violent_felony_df = violent_felony_df.drop(columns=cols_to_drop)
violent_felony_df.head()

,CMPLNT_FR_DT,CMPLNT_FR_TM,ADDR_PCT_CD,RPT_DT,OFNS_DESC,CRM_ATPT_CPTD_CD,JURIS_DESC,X_COORD_CD,Y_COORD_CD,SUSP_AGE_GROUP,SUSP_RACE,SUSP_SEX,Latitude,Longitude,Lat_Lon,PATROL_BORO,STATION_NAME,time_period
8147,2019-12-18,00:01:00,9.0,12/26/2024,RAPE,COMPLETED,N.Y. POLICE DEPT,"987,496","203,963",UNKNOWN,BLACK,M,40.726516,-73.988290,"(40.7265156408036, -73.9882902437563)",PATROL BORO MAN SOUTH,(null),after Patternizr
11329,2017-01-01,12:00:00,107.0,12/23/2024,SEX CRIMES,COMPLETED,N.Y. POLICE DEPT,"1,036,658","205,330",UNKNOWN,UNKNOWN,M,40.730113,-73.810909,"(40.7301130668694, -73.8109089148815)",PATROL BORO QUEENS SOUTH,(null),after Patternizr
11817,2003-01-01,00:00:00,109.0,12/22/2024,SEX CRIMES,COMPLETED,N.Y. POLICE DEPT,"1,032,051","217,053",25-44,UNKNOWN,M,40.762316,-73.827448,"(40.7623158004241, -73.8274480018593)",PATROL BORO QUEENS NORTH,(null),before Patternizr
16934,2017-06-01,12:00:00,42.0,12/19/2024,RAPE,COMPLETED,N.Y. POLICE DEPT,"1,008,690","238,862",25-44,WHITE HISPANIC,M,40.822271,-73.911698,"(40.8222710411331, -73.911697780277)",PATROL BORO BRONX,(null),after Patternizr
16988,2014-01-01,00:01:00,32.0,12/19/2024,SEX CRIMES,COMPLETED,N.Y. HOUSING POLICE,"999,433","236,538",UNKNOWN,WHITE HISPANIC,M,40.815913,-73.945149,"(40.81591307653, -73.9451493066481)",PATROL BORO MAN NORTH,(null),after Patternizr

In [33]:
violent_felony_df["CMPLNT_FR_DT"] = pd.to_datetime(
    violent_felony_df["CMPLNT_FR_DT"], errors="coerce"
)

cutoff = pd.Timestamp("2013-08-01")

violent_felony_df["time_period"] = np.where(
    violent_felony_df["CMPLNT_FR_DT"] <= cutoff,
    "before Patternizr",
    "after Patternizr"
)

violent_felony_df["time_period"].value_counts()

/var/folders/37/mv21yn416f54tz95t9pwzqxm0000gn/T/ipykernel_6774/503354933.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  violent_felony_df["CMPLNT_FR_DT"] = pd.to_datetime(
/var/folders/37/mv21yn416f54tz95t9pwzqxm0000gn/T/ipykernel_6774/503354933.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  violent_felony_df["time_period"] = np.where(

time_period
before Patternizr    518785
after Patternizr     374464
Name: count, dtype: int64

In [39]:
violent_felony_df = violent_felony_df.dropna()
violent_felony_df.isna().sum()
violent_felony_df["time_period"].value_counts()
violent_felony_df.head()

,CMPLNT_FR_DT,CMPLNT_FR_TM,ADDR_PCT_CD,RPT_DT,OFNS_DESC,CRM_ATPT_CPTD_CD,JURIS_DESC,X_COORD_CD,Y_COORD_CD,SUSP_AGE_GROUP,SUSP_RACE,SUSP_SEX,Latitude,Longitude,Lat_Lon,PATROL_BORO,STATION_NAME,time_period
8147,2019-12-18,00:01:00,9.0,12/26/2024,RAPE,COMPLETED,N.Y. POLICE DEPT,"987,496","203,963",UNKNOWN,BLACK,M,40.726516,-73.988290,"(40.7265156408036, -73.9882902437563)",PATROL BORO MAN SOUTH,(null),after Patternizr
11329,2017-01-01,12:00:00,107.0,12/23/2024,SEX CRIMES,COMPLETED,N.Y. POLICE DEPT,"1,036,658","205,330",UNKNOWN,UNKNOWN,M,40.730113,-73.810909,"(40.7301130668694, -73.8109089148815)",PATROL BORO QUEENS SOUTH,(null),after Patternizr
11817,2003-01-01,00:00:00,109.0,12/22/2024,SEX CRIMES,COMPLETED,N.Y. POLICE DEPT,"1,032,051","217,053",25-44,UNKNOWN,M,40.762316,-73.827448,"(40.7623158004241, -73.8274480018593)",PATROL BORO QUEENS NORTH,(null),before Patternizr
16934,2017-06-01,12:00:00,42.0,12/19/2024,RAPE,COMPLETED,N.Y. POLICE DEPT,"1,008,690","238,862",25-44,WHITE HISPANIC,M,40.822271,-73.911698,"(40.8222710411331, -73.911697780277)",PATROL BORO BRONX,(null),after Patternizr
16988,2014-01-01,00:01:00,32.0,12/19/2024,SEX CRIMES,COMPLETED,N.Y. HOUSING POLICE,"999,433","236,538",UNKNOWN,WHITE HISPANIC,M,40.815913,-73.945149,"(40.81591307653, -73.9451493066481)",PATROL BORO MAN NORTH,(null),after Patternizr

In [40]:
violent_felony_df.to_csv("violent_felony_cleaned.csv", index=False)